# Generated by Django 5.0.6 on 2026-10-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_promo_order_discount_order_promo_code_order_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, help_text='Comma-separated colour names in stock order, e.g. Black, Dark Brown, Caramel', max_length=300),
        ),
    ]
