# Generated by Django 5.0.6 on 2026-10-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='bg_luma',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Mean brightness of the pixels around the photo edge, 0-255. Measured by the tag_image_backgroups command; ~225+ means a plain white studio backdrop.', null=True),
        ),
    ]
