# Generated by Django 5.0.6 on 2026-10-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productimage_bg_luma'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='shows_person',
            field=models.BooleanField(default=False, help_text='Tick when a model, hands or a body appear in this photo. The Trending band skips these.'),
        ),
    ]
