# Generated by Django 5.0.6 on 2026-10-02 13:06

from django.db import migrations, models


def copy_from_shows_person(apps, schema_editor):
    ProductImage = apps.get_model("store", "ProductImage")
    ProductImage.objects.filter(shows_person=True).update(band_ready=False)


def copy_back(apps, schema_editor):
    ProductImage = apps.get_model("store", "ProductImage")
    ProductImage.objects.filter(band_ready=False).update(shows_person=True)


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_productimage_shows_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="band_ready",
            field=models.BooleanField(
                default=True,
                help_text="The bag alone on a plain backdrop: no model or hands, no second item, no "
                          "watermark strip. The Trending band only uses photos with this ticked; untick "
                          "to bench a photo.",
            ),
        ),
        migrations.RunPython(copy_from_shows_person, copy_back),
        migrations.RemoveField(model_name="productimage", name="shows_person"),
    ]
