"""
Django settings for kibetistore project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import mimetypes
import os
import urllib.parse
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Daraja credentials live in .env, not in this file. Must run before store/payments.py is imported,
# since it reads its configuration from os.environ at import time.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from the environment (set in .env); never hardcode or commit it.
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

ON_VERCEL = bool(os.environ.get("VERCEL"))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False" if ON_VERCEL else "True") == "True"

ALLOWED_HOSTS = [h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h]
if ON_VERCEL:
    ALLOWED_HOSTS += [".vercel.app"]
    ALLOWED_HOSTS += [
        os.environ[k] for k in ("VERCEL_URL", "VERCEL_BRANCH_URL", "VERCEL_PROJECT_PRODUCTION_URL")
        if os.environ.get(k)
    ]

CSRF_TRUSTED_ORIGINS = [f"https://{h.lstrip('.')}" if not h.startswith(".") else f"https://*{h}"
                        for h in ALLOWED_HOSTS if h not in ("localhost", "127.0.0.1")]

if ON_VERCEL:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
    SECURE_HSTS_SECONDS = 63072000


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kibetistore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.store_nav',
            ],
        },
    },
]

WSGI_APPLICATION = 'kibetistore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Vercel's filesystem is read-only and ephemeral, so SQLite only works locally. When the Supabase
# integration's POSTGRES_URL is present, use it (it's the transaction pooler, which suits serverless).
_database_url = os.environ.get("DATABASE_URL") or os.environ.get("POSTGRES_URL")
if _database_url:
    _db = urllib.parse.urlparse(_database_url)
    _query = urllib.parse.parse_qs(_db.query)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _db.path.lstrip('/') or 'postgres',
            'USER': urllib.parse.unquote(_db.username or ''),
            'PASSWORD': urllib.parse.unquote(_db.password or ''),
            'HOST': _db.hostname,
            'PORT': _db.port or 5432,
            'CONN_MAX_AGE': 0,
            # Transaction-mode poolers (pgbouncer/Supavisor) don't support server-side cursors.
            'DISABLE_SERVER_SIDE_CURSORS': True,
            'OPTIONS': {'sslmode': _query.get('sslmode', ['require'])[0]},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Vercel's Python runtime never runs collectstatic, so WhiteNoise serves straight from the
# finders (static/ plus app static such as the admin) instead of a collected STATIC_ROOT.
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = DEBUG

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Windows resolves mimetypes from the registry, which has no image/webp entry — without this,
# .webp files under MEDIA_ROOT are served as application/octet-stream.
mimetypes.add_type('image/webp', '.webp')

LOGIN_URL = 'login'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
